openapi: 3.0.0
info:
  title: Main
  description: >-
    # Servers and Resources


    LP (Licensing Platform) -
    [https://music.clicknclear.com](https://music.clicknclear.com)  

    LP API -
    [https://music.clicknclear.com/api](https://music.clicknclear.com/api)  

    LVS (License Verification System) -
    [https://verification.clicknclear.com](https://verification.clicknclear.com)  

    LVS API -
    [https://verification.clicknclear.com/api](https://verification.clicknclear.com/api)  

    Support Email - [support@clicknclear.com](mailto:support@clicknclear.com)  

    Tech Team Email -
    [techteam@clicknclear.com](mailto:techteam@clicknclear.com)


    # API Keys


    To create an API key please make sure you first contact a ClicknClear admin
    so they can enable API Key support for your user account.


    ## Api Key Setup


    *   Navigate to
    [https://music.clicknclear.com/profile](https://music.clicknclear.com/profile)
    (login if you are not)

    *   If your account is setup correctly you should have an "API Keys"
    section. If you cannot see this section please get in contact via the
    support email or the tech team email.

    *   Click on the "Create API Key" button

    *   Enter a name for the API Key, this is to help you identify it at a later
    date

    *   Copy the API key and store it somewhere safe, you will not be able to
    view it again.
        

    # Authentication


    See the Login routes for more information on how to get Access Token and
    Refresh Tokens.  

    Once you have your access token you should Add the "Authorization" header
    with the value of "Bearer {YOUR_API_KEY}" to every one of your ClicknClear
    API requests.


    EG:


    ```

    'Authorzation': 'Bearer $2b$04$j7...'


    ```


    # Server Responses


    Throughout our APIs we heavily utilise [HTTP
    Codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) to signify
    the status of the request. In general, a 4xx status code will have the error
    type and usually a message to help the developer know why the request
    failed. Below is an example of an erroneous login request.


    ```

    {
        "statusCode": 400,
        "error": "Bad Request",
        "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"apiKey\"\n    ],\n    \"message\": \"Required\"\n  }\n]"
    }


    ```


    If you are consistently receiving 400s or even 500s and you're not sure how
    to fix it please email the Tech Team email with steps to reproduce your
    issue.
  version: 1.0.0
servers:
  - url: https://music.clicknclear.com/api
    description: Used for authentication
  - url: https://verification.clicknclear.com/api
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
  - name: Revenue Streams
  - name: Organisations
paths:
  /auth/api-key/login:
    post:
      tags:
        - Auth
      summary: Login
      description: >-
        This endpoint should be used to get an access token and a refresh token
        from an API Key. Once the access token is fetched it should be used to
        authenticate to other API endpoints
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                apiKey: '{{apiKey}}'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 15 Jun 2022 20:44:56 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            vary:
              schema:
                type: string
                example: Origin
            x-ratelimit-limit:
              schema:
                type: integer
                example: '25'
            x-ratelimit-remaining:
              schema:
                type: integer
                example: '23'
            x-ratelimit-reset:
              schema:
                type: integer
                example: '43'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                accessTokenExpiresIn: 86400
                refreshTokenExpiresIn: 604800
                accessToken: ...
                refreshToken: ..
  /auth/access-token/refresh:
    post:
      tags:
        - Auth
      summary: Refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refreshToken: '{{refreshToken}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 15 Jun 2022 20:47:06 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            vary:
              schema:
                type: string
                example: Origin
            x-ratelimit-limit:
              schema:
                type: integer
                example: '1000'
            x-ratelimit-remaining:
              schema:
                type: integer
                example: '997'
            x-ratelimit-reset:
              schema:
                type: integer
                example: '38'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                accessToken: ...
                accessTokenExpiresIn: 86400
  /revenue-streams/upload:
    post:
      tags:
        - Revenue Streams
      summary: Recording Upload
      description: Revenue Stream Sound Recording upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                metadata:
                  type: string
                  description: >-

                    JSON string of the Metadata relating to the file uploaded.
                    Metadata  

                    must come before recording file.


                    Metadata Shape:


                    ``` typescript

                    {
                        //startDate - the date the recording became live
                        startDate: string

                        //endDate - (optional) the date the recording will be taken down
                        endDate?: string

                        //externalId - (optional) the external id of the sound recording 
                        externalId?: string

                        //organisationId - the ClicknClear id of the organisation who this sound recording belongs to.
                        organisationId: number

                       //uploadUseType - how this sound recording will be used
                       uploadUseType: "Video On Demand" | "Live Stream"

                       //onFinishedMatchingCallBackURL - (optional) an optional call back url which will be called via a POST request once the upload has finished the matching process
                       onFinishedMatchingCallBackURL?: string
                    }


                    ```
                  example: |-
                    {
                      "externalId": "123",
                      "organisationId": 1,
                      "startDate": "2022-01-01",
                      "uploadUseType": "Video On Demand",
                      "onFinishedMatchingCallBackURL": "{{callbackServerUrl}}"
                    }
                '':
                  type: string
                  description: >-
                    The file of the sound recording ot be verified. Accepted
                    Mime Types: 'audio/mpeg', 'audio/vnd.wav', 'audio/wave',
                    'audio/wav', 'audio/x-wav', 'audio/x-pn-wav', 'audio/mp3',
                    'audio/mp4'
                  format: binary
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 15 Jun 2022 21:56:59 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                id: 4
                soundRecordingId: 83
                startDate: '2022-01-01T00:00:00.000Z'
                endDate: null
                streamId: 2
                soundRecording:
                  id: 83
                  duration: 136.6987755102041
                  uploadFilename: MY_MIX_WITH_MATCHES.mp3
                  matchingClipLength: 10
                  status: Matching
                  uploaderUserId: 1228
                  createdAt: '2022-06-15T21:56:59.126Z'
                  deletedAt: null
                  updatedAt: '2022-06-15T21:56:59.000Z'
                  licenses: []
                  matches: []
                  muteTimes:
                    - start: 0
                      end: 136.6987755102041
                status: Processing
  /revenue-streams/upload-url:
    post:
      tags:
        - Revenue Streams
      summary: Recording Upload URL
      description: >-
        This endpoint should be used to deliver recordings for verification via
        a provided URL (fileDownloadURL). All files will be fetched via a simple
        get requests so if the download requires authentication it will need to
        be in the URL. The fetch has a 15minute timeout to download and convert
        the file so it is important that the download speed of the file is good.


        This endpoint accepts any FFMPEG compatible file formats and will
        download and strip just the audio element before verification.  

        Body Schema:


        ```

        { 

        //startDate - the date the recording became live 

        startDate: string

        //endDate - (optional) the date the recording will be taken down 

        endDate?: string 

        //externalId - (optional) the external id of the sound recording 

        externalId?: string 

        //organisationId - the ClicknClear id of the organisation who this sound
        recording belongs to. 

        organisationId: number

        //fileDownloadURL - a link to the file to be uploaded 

        fileDownloadURL: string 

        //uploadUseType - how this sound recording will be used 

        uploadUseType: "Video On Demand" | "Live Stream" 

        //onFinishedMatchingCallBackURL - (optional) an optional call back url
        which will be called via POST request once the upload has finished the
        matching process. The shape of the data posted is the same as the Get
        Revenue Stream Recording Request 

        onFinishedMatchingCallBackURL?: string 

        }


        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                externalId: '123'
                organisationId: 1
                startDate: '2022-01-01'
                uploadUseType: Video On Demand
                fileDownloadURL: '{{fileDownloadURL}}'
                onFinishedMatchingCallBackURL: '{{callbackServerUrl}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Tue, 16 Aug 2022 12:23:37 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                id: 7
                soundRecordingId: 17
                startDate: '2022-01-01T00:00:00.000Z'
                endDate: null
                streamId: 2
                soundRecording:
                  id: 17
                  duration: 0
                  uploadFilename: null
                  matchingClipLength: 10
                  status: Downloading
                  uploaderUserId: 589
                  createdAt: '2022-08-16T12:23:37.420Z'
                  deletedAt: null
                  updatedAt: '2022-08-16T12:23:37.000Z'
                  licenses: []
                  matches: []
                  muteTimes:
                    - start: 0
                      end: 0
                status: No Matches Found
  /revenue-streams/recordings/{revenueStreamRecordingId}:
    patch:
      tags:
        - Revenue Streams
      summary: Revenue Stream Recording
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                startDate: '2022-01-02'
                endDate: '2023-01-02'
      parameters:
        - name: revenueStreamRecordingId
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '204':
          description: No Content
          headers:
            Date:
              schema:
                type: string
                example: Wed, 15 Jun 2022 21:59:09 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
          content:
            text/plain:
              schema:
                type: string
              example: null
  /revenue-streams/recordings/{id}:
    get:
      tags:
        - Revenue Streams
      summary: Revenue Stream Recording
      description: |-
        Gets the revenue stream recording by id

        Revenue Stream Sound Recording Response Type:

        ```
        {
            //Revenue Stream Sound Recording (RSSR) Id
            "id": 20,
            //Sound Recording Id (you can have a Sound Recording associated with multiple Revenue Stream Sound Recordings)
            "soundRecordingId": 48,
            //When the RSSR started attributing to revenues
            "startDate": "2022-01-02T00:00:00.000Z",
            //When the RSSR stopped attributing to revenues
            "endDate": "2023-01-02T00:00:00.000Z",
            //The Id of the revenue stream the RSSR is associated to
            "streamId": 5,
            //The overall status of the RSSR possible values are:
            //Licensed - the RSSR is fully licensed
            //"Partially Licensed" - Not all of the matches found are covered by the organisation license agreement
            //"No Matches Found" - No matches were found for this RSSR
            //Unlicensed - none of the matches found have matched with any license agreements
            //Processing - The RSSR is still processing and so a license status is not known at this time
            "status": "Licensed"
            //The sound recording data which is attached to the revenue stream
            "soundRecording": {
                //The Id of the sound recording (SR)
                "id": 48,
                //The calculated duration of the SR (seconds)
                "duration": 60.00326530612245,
                //The name of the file when it was uploaded
                "uploadFilename": "LiveSTreamingVODTrack_SHORT.mp3",
                //The size of the chunks used when verifying
                "matchingClipLength": 10,
                // The status of the sound recording, possible values below
                //Uploading - This status is set when the recording has reached the server and is being uploaded into permanent storage  
                //Created - This status is the default status when a recording is initially created but nothing has happened yet  
                //Downloading - This status is set when a recording is created via the "Recording Upload URL" route and the uploaded file has not finished downloading
                //Uploaded - This status is set just after the recording has been uploaded into permanent storage  
                //Matching - This status is set when the recording has been sent for Verification and Audio Recognition matching  
                //Complete - This status is set after matching has been completed and no further processing of this recording is required  
                //Failed - This status is set when the recording errors at any point of its workflow.
                "status": "Complete",
                //The Id of the user who uploaded the sound recording
                "uploaderUserId": 767,
                //The licenses matched against this recording. This will usually be empty for revenue streams
                "licenses": [],
                //If unlicensed music was detected mute timestamps are generated where the unlicensed music is played
                "muteTimes": []
                //An array of all of the matches found on this sound recording
                //If a match does not have an lpId or an rmdId - we do not have the track in our catalogue
                //If it has an rmdId but no lpId -  we have the track but cannot legally sell it
               //If it has an lpId - this track was/is live on licensing platform and can be found at https://music.clicknclear.com
                "matches": [
                    {
                        //The sound recording match (SRM) id
                        "id": 1038,
                        //The title of this match
                        "title": "Hawthorne's Most Wanted",
                        //Comma separated list of artists
                        "artists": "rocdomz",
                        //The start time (seconds) this match was detected in the SR
                        "startTime": 0,
                        //The end time (seconds) this match was detected in the SR
                        "endTime": 10,
                        //The ClicknClear licensing platforms (LP) track Id of this match
                        "lpId": 21127,
                        //The ClicknClear rights management database (RMD) track Id of this match
                        "rmdId": "5e9651bfbdd27a2e43b2ca58",
                        //The acr id of this match
                        "acrId": "f758eb6fb4c4ae041ecb2b543226a8aa",
                        //The licensing status of this match possible values are:
                        //Ok - This match has been verified as fully licensed given the current context
                        //Expired - A license was found for this match but it is now expired
                        //Missing - No license can be found for this match
                        "status": "Ok",
                        "createdAt": "2022-06-08T12:22:45.205Z",
                        "updatedAt": "2022-06-08T12:22:45.205Z",
                        "deletedAt": null,
                        "licenseIds": [],
                        "isrc": "USACX0701355",
                        "upc": "899090926204",
                        "matchScore": 100,
                        "tunecode": null
                    }
                ],
                "createdAt": "2022-06-08T12:22:35.567Z",
                "deletedAt": null,
                "updatedAt": "2022-06-08T12:22:45.000Z"
            }
        }

        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: OK
          headers:
            content-type:
              schema:
                type: string
                example: application/json; charset=utf-8
            content-length:
              schema:
                type: integer
                example: '2906'
            Date:
              schema:
                type: string
                example: Wed, 08 Jun 2022 15:55:31 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Licensed Revenue Stream Recording
                  value:
                    id: 20
                    soundRecordingId: 48
                    startDate: '2022-01-02T00:00:00.000Z'
                    endDate: '2023-01-02T00:00:00.000Z'
                    streamId: 5
                    soundRecording:
                      id: 48
                      s3Path: c20d76432011207efda77bf21df9a37c.mp3
                      s3Bucket: cnc-sound-recordings-staging
                      duration: 60.00326530612245
                      uploadFilename: LiveSTreamingVODTrack_SHORT.mp3
                      matchingClipLength: 10
                      status: Complete
                      uploaderUserId: 767
                      awsChecksum: '"c20d76432011207efda77bf21df9a37c"'
                      createdAt: '2022-06-08T12:22:35.567Z'
                      deletedAt: null
                      updatedAt: '2022-06-08T12:22:45.000Z'
                      licenses: []
                      matches:
                        - id: 1038
                          startTime: 0
                          endTime: 10
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                        - id: 1038
                          startTime: 10
                          endTime: 20
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                        - id: 1038
                          startTime: 20
                          endTime: 30
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                        - id: 1038
                          startTime: 30
                          endTime: 40
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                        - id: 1038
                          startTime: 40
                          endTime: 50
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                        - id: 1038
                          startTime: 50
                          endTime: 60
                          lpId: 21127
                          rmdId: 5e9651bfbdd27a2e43b2ca58
                          acrId: f758eb6fb4c4ae041ecb2b543226a8aa
                          title: Hawthorne's Most Wanted
                          isrc: USACX0701355
                          upc: '899090926204'
                          matchScore: 100
                          tunecode: null
                          artists: rocdomz
                          createdAt: '2022-06-08T12:22:45.205Z'
                          updatedAt: '2022-06-08T12:22:45.205Z'
                          deletedAt: null
                          status: Ok
                          licenseIds: []
                      muteTimes: []
                    status: Licensed
                example-1:
                  summary: No Matches Revenue Stream Recording
                  value:
                    id: 17
                    soundRecordingId: 45
                    startDate: '2022-01-01T00:00:00.000Z'
                    endDate: null
                    streamId: 4
                    soundRecording:
                      id: 45
                      duration: 10.031020408163265
                      uploadFilename: MY_MIX_WITH_MATCHES.mp3
                      matchingClipLength: 10
                      status: Complete
                      uploaderUserId: 589
                      createdAt: '2022-06-08T10:56:20.226Z'
                      deletedAt: null
                      updatedAt: '2022-06-08T10:56:28.000Z'
                      licenses: []
                      matches: []
                      muteTimes:
                        - start: 0
                          end: 10.031020408163265
                    status: No Matches Found
                example-2:
                  summary: Unlicensed Revenue Stream Recording
                  value:
                    id: 4
                    soundRecordingId: 83
                    startDate: '2022-01-02T00:00:00.000Z'
                    endDate: '2023-01-02T00:00:00.000Z'
                    streamId: 2
                    soundRecording:
                      id: 83
                      duration: 136.6987755102041
                      uploadFilename: MY_MIX_WITH_MATCHES.mp3
                      matchingClipLength: 10
                      status: Complete
                      uploaderUserId: 1228
                      createdAt: '2022-06-15T21:56:59.126Z'
                      deletedAt: null
                      updatedAt: '2022-06-15T21:57:12.000Z'
                      licenses: []
                      matches:
                        - id: 1884
                          startTime: 0
                          endTime: 10
                          lpId: 250484
                          rmdId: 5f4c01476fce45507bab88d5
                          acrId: c32ee2dd858ef02ec1a8954ea7654f89
                          title: Up All Night
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.829Z'
                          updatedAt: '2022-06-15T21:57:12.829Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1884
                          startTime: 10
                          endTime: 20
                          lpId: 250484
                          rmdId: 5f4c01476fce45507bab88d5
                          acrId: c32ee2dd858ef02ec1a8954ea7654f89
                          title: Up All Night
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.829Z'
                          updatedAt: '2022-06-15T21:57:12.829Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1892
                          startTime: 20
                          endTime: 30
                          lpId: 165186
                          rmdId: 5f4c92666fce45507bf93b92
                          acrId: 05395cf0cedde470c3f631a0eb28c298
                          title: I Should Have Kissed You
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.869Z'
                          updatedAt: '2022-06-15T21:57:12.869Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1892
                          startTime: 30
                          endTime: 40
                          lpId: 165186
                          rmdId: 5f4c92666fce45507bf93b92
                          acrId: 05395cf0cedde470c3f631a0eb28c298
                          title: I Should Have Kissed You
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.869Z'
                          updatedAt: '2022-06-15T21:57:12.869Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1892
                          startTime: 40
                          endTime: 50
                          lpId: 165186
                          rmdId: 5f4c92666fce45507bf93b92
                          acrId: 05395cf0cedde470c3f631a0eb28c298
                          title: I Should Have Kissed You
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.869Z'
                          updatedAt: '2022-06-15T21:57:12.869Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1892
                          startTime: 50
                          endTime: 60
                          lpId: 165186
                          rmdId: 5f4c92666fce45507bf93b92
                          acrId: 05395cf0cedde470c3f631a0eb28c298
                          title: I Should Have Kissed You
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.869Z'
                          updatedAt: '2022-06-15T21:57:12.869Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1884
                          startTime: 80
                          endTime: 90
                          lpId: 250484
                          rmdId: 5f4c01476fce45507bab88d5
                          acrId: c32ee2dd858ef02ec1a8954ea7654f89
                          title: Up All Night
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.829Z'
                          updatedAt: '2022-06-15T21:57:12.829Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                        - id: 1884
                          startTime: 90
                          endTime: 100
                          lpId: 250484
                          rmdId: 5f4c01476fce45507bab88d5
                          acrId: c32ee2dd858ef02ec1a8954ea7654f89
                          title: Up All Night
                          isrc: null
                          upc: null
                          matchScore: 100
                          tunecode: null
                          artists: One Direction
                          createdAt: '2022-06-15T21:57:12.829Z'
                          updatedAt: '2022-06-15T21:57:12.829Z'
                          deletedAt: null
                          status: Missing
                          licenseIds: []
                      muteTimes:
                        - start: 0
                          end: 10
                        - start: 10
                          end: 20
                        - start: 20
                          end: 30
                        - start: 30
                          end: 40
                        - start: 40
                          end: 50
                        - start: 50
                          end: 60
                        - start: 60
                          end: 70
                        - start: 70
                          end: 80
                        - start: 80
                          end: 90
                        - start: 90
                          end: 100
                        - start: 100
                          end: 110
                        - start: 110
                          end: 120
                        - start: 120
                          end: 130
                        - start: 130
                          end: 136.6987755102041
                    status: Unlicensed
  /orgs/me:
    get:
      tags:
        - Organisations
      summary: Get My Organisations
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 15 Jun 2022 20:58:58 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            vary:
              schema:
                type: string
                example: Origin
            x-ratelimit-limit:
              schema:
                type: integer
                example: '1000'
            x-ratelimit-remaining:
              schema:
                type: integer
                example: '999'
            x-ratelimit-reset:
              schema:
                type: integer
                example: '46'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                - createdAt: '2022-04-29T10:10:49.513Z'
                  deletedAt: null
                  id: 3
                  name: ClicknClear
                  parentId: null
                  updatedAt: '2022-06-06T11:50:16.000Z'
                  isEventProducer: true
                  users:
                    - id: 589
                      name: Tristan Barlow
                      email: tristan@clicknclear.com
                      created: '2021-02-12T10:42:29.000Z'
                      isActive: 1
                      currency: USD
                      language: en-gb
                      permissions: []
                      orgPermissions:
                        shared:
                          - Event.Manage
                          - Event.View
                          - Owner
                          - Revenue.Manage
                        perOrg:
                          '3':
                            - Event.Manage
                            - Event.View
                            - Owner
                            - Revenue.Manage
                  licenseAgreementLiveStreamingRevenueShare: 10
                  licenseAgreementVODRevenueShare: 10
                  hasLicenseAgreement: true
                  licenseAgreementStart: null
                  licenseAgreementEnd: null
                  webHookOnChildCompanySignUp: null
                  freeTierUsageAmount: null
                  externalId: null
                  useParentOrgUsage: false
